### ISSUE TITLE
Strong Customer Authentication / PSD2 (critical if your startup is EU based)

### ISSUE THREAD

**Issue by GavBaros** [florianmari/appreliability.co#4]
Please fill and explain the choice of your control point

**Name (mandatory)**
Add Strong Customer Authentication 

**Chronology (mandatory)**
Before development

**Level or priority (mandatory)**
high

**Details (mandatory)**
EU Payments Services Directive (PSD2) has been delayed by about 2 years for EU businesses (at least in the UK) but all FE and BE payment flows **must** be designed with SCA steps in mind, especially if you have complex payments flows and processes, otherwise face disruption to your revenues as soon as PSD2 is official.

**Principle (optional)**
Single Source Of Truth, Separation Of Concerns...

**Comment by florianmari** [comment]
Hello! Thank you for this point, it is very interesting and deserves to be on the list, I can add it for you or I let you do a PR

Thank you so much for your contribution

**Comment by GavBaros** [comment]
Hey Florian, thanks for this project it is quite useful for many people. Feel free to add it yourself 👍

**Comment by florianmari** [comment]
Thank you! I added your contribution
